### ISSUE TITLE
Remove unneeded dependencies

### ISSUE THREAD

**Issue by sanmai-NL** [christopher-hacker/enforce-notebook-run-order#10]
You depend on `psutil`, but don't use it. `psutil` then needs Linux kernel header files to compile. This is all quite hefty a dependency.

You can use [Creosote](https://github.com/fredrikaverpil/creosote) to detect such unneeded dependencies.

**Comment by jamesmyatt** [comment]
Looks to me like it's a dependency of ipykernel: https://github.com/christopher-hacker/enforce-notebook-run-order/blob/7bc746f9324907514498dd4f5ad125727072049e/poetry.lock#L909
