### ISSUE TITLE
False positive on empty cells at the end of files

### ISSUE THREAD

**Issue by jamesmyatt** [christopher-hacker/enforce-notebook-run-order#13]
Jupyter often adds an empty code cell at the end of the file when editing, which Jupyter never runs (because it's empty). I think that flagging these cells is a false positive. Can you ignore them? Note that the `source` is empty (see below).

There's a question about whether all empty code cells should be permitted, but I think an empty code cell at the end of the file should certainly be permitted.

```
Code cell was not run. The previous cell was #24.

Cell contents:

> {'cell_type': 'code', 'execution_count': None, 'id': '1309e80c-b330-4b54-99eb-ef127a838ebb', 'metadata': {}, 'outputs': [], 'source': []}
```

**Comment by christopher-hacker** [comment]
Thanks for the suggestion. I agree, this is now the default behavior.
